<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <RootNamespace>FTC.TeamDesk.AI</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\FTC.TeamDesk.Core\FTC.TeamDesk.Core.csproj" />
    <ProjectReference Include="..\FTC.TeamDesk.Security\FTC.TeamDesk.Security.csproj" />
  </ItemGroup>
</Project>
